#!C:\Users\RAJ\AppData\Local\Programs\Python\Python36\python
print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<title>Hello Word - First CGI Program</title>')
print('</head>')
print('<body>')
print("<?php echo 'PATH_INFO'; ?>")
print('<h2>Hello Word! This is my first CGI program</h2>')
print('</body>')
print('</html>')
